# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ziYIUKT7M_gNTQ04QbFN6OLKeny6nFUC
"""

import os

os.makedirs("project1_diagnostics", exist_ok=True)

print("Project 1 folder created successfully.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile project1_diagnostics/diagnostics.py
# 
# import sys
# import os
# import shutil
# import json
# 
# 
# def check_python_version():
#     version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
# 
#     return {
#         "check": "Python Version",
#         "version": version,
#         "status": "OK"
#     }
# 
# 
# def check_disk_space():
#     total, used, free = shutil.disk_usage("/")
# 
#     free_gb = free / (1024 ** 3)
# 
#     status = "OK" if free_gb > 1 else "WARNING"
# 
#     return {
#         "check": "Disk Space",
#         "free_gb": round(free_gb, 2),
#         "status": status
#     }
# 
# 
# def check_environment_variable(variable_name):
#     value = os.environ.get(variable_name)
# 
#     if value:
#         status = "OK"
#     else:
#         status = "MISSING"
# 
#     return {
#         "check": f"Environment Variable: {variable_name}",
#         "value": value if value else "Not Set",
#         "status": status
#     }
# 
# 
# def check_command(command):
#     path = shutil.which(command)
# 
#     if path:
#         status = "OK"
#     else:
#         status = "MISSING"
# 
#     return {
#         "check": f"Developer Tool: {command}",
#         "path": path if path else "Not Found",
#         "status": status
#     }
# 
# 
# def run_diagnostics():
#     results = []
# 
#     results.append(check_python_version())
#     results.append(check_disk_space())
# 
#     # Check a common environment variable
#     results.append(check_environment_variable("PATH"))
# 
#     # Check common developer tools
#     results.append(check_command("python"))
#     results.append(check_command("git"))
# 
#     return results
# 
# 
# def print_human_readable(results):
#     print("=" * 50)
#     print("SYSTEM DIAGNOSTICS REPORT")
#     print("=" * 50)
# 
#     for result in results:
#         print(f"\nCheck: {result['check']}")
# 
#         for key, value in result.items():
#             if key != "check":
#                 print(f"{key}: {value}")
# 
#     print("\n" + "=" * 50)
# 
# 
# def save_json(results, filename="diagnostics_report.json"):
#     with open(filename, "w") as file:
#         json.dump(results, file, indent=4)
# 
#     print(f"JSON report saved to: {filename}")

import sys

sys.path.append("/content/project1_diagnostics")

from diagnostics import run_diagnostics, print_human_readable, save_json

results = run_diagnostics()

print_human_readable(results)

save_json(results)

import sys

sys.path.append("/content/project1_diagnostics")

from diagnostics import run_diagnostics, print_human_readable, save_json

results = run_diagnostics()

print_human_readable(results)

save_json(results)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile project1_diagnostics/cli.py
# 
# import argparse
# from diagnostics import run_diagnostics, print_human_readable, save_json
# 
# 
# def main():
#     parser = argparse.ArgumentParser(
#         description="Python System Diagnostics Tool"
#     )
# 
#     parser.add_argument(
#         "--json",
#         action="store_true",
#         help="Save diagnostics as JSON"
#     )
# 
#     args = parser.parse_args()
# 
#     results = run_diagnostics()
# 
#     print_human_readable(results)
# 
#     if args.json:
#         save_json(results)
# 
# 
# if __name__ == "__main__":
#     main()

!cd project1_diagnostics && python cli.py --json