# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HF20qUUOS5Dq9Z0clqL0VHnbrpAh9YOG
"""

!pip install requests beautifulsoup4 pandas -q

import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import time

def scrape_quotes(pages=5):

    base_url = "https://quotes.toscrape.com/page/{}/"

    records = []

    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    for page in range(1, pages + 1):

        url = base_url.format(page)

        print("Scraping:", url)

        try:
            response = requests.get(
                url,
                headers=headers,
                timeout=10
            )

            response.raise_for_status()

            soup = BeautifulSoup(
                response.text,
                "html.parser"
            )

            quotes = soup.find_all(
                "div",
                class_="quote"
            )

            for quote in quotes:

                text = quote.find(
                    "span",
                    class_="text"
                ).get_text(strip=True)

                author = quote.find(
                    "small",
                    class_="author"
                ).get_text(strip=True)

                tags = [
                    tag.get_text(strip=True)
                    for tag in quote.find_all(
                        "a",
                        class_="tag"
                    )
                ]

                records.append({
                    "quote": text,
                    "author": author,
                    "tags": ", ".join(tags)
                })

            # Rate limiting
            time.sleep(1)

        except requests.RequestException as e:

            print("Request failed:", e)

    return records

data = scrape_quotes(5)

print("Total records:", len(data))

df = pd.DataFrame(data)

df.head(10)

df.to_csv(
    "quotes_data.csv",
    index=False
)

print("CSV file created successfully.")

df.to_json(
    "quotes_data.json",
    orient="records",
    indent=4
)

print("JSON file created successfully.")

print("Total quotes:", len(df))

print(
    "Number of authors:",
    df["author"].nunique()
)

print("\nTop authors:")

print(
    df["author"].value_counts().head(10)
)

from collections import Counter

all_tags = []

for tags in df["tags"]:
    all_tags.extend(
        [tag.strip() for tag in tags.split(",")]
    )

tag_counts = Counter(all_tags)

print("Most common tags:")

for tag, count in tag_counts.most_common(10):
    print(tag, ":", count)

summary = {
    "total_quotes": len(df),
    "unique_authors": int(df["author"].nunique()),
    "unique_tags": len(tag_counts),
    "top_author": (
        df["author"].value_counts().index[0]
        if len(df) > 0
        else None
    ),
    "top_tag": (
        tag_counts.most_common(1)[0][0]
        if tag_counts
        else None
    )
}

print(json.dumps(summary, indent=4))

with open(
    "scraping_analysis_report.json",
    "w"
) as file:

    json.dump(
        summary,
        file,
        indent=4
    )

print("Analysis report saved.")