# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkSV2ZzHLxGdQjc2iEC3D6oDA14NZpCz
"""

!pip install fastapi uvicorn pyjwt passlib[bcrypt] python-multipart nest-asyncio requests -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile project4_api.py
# 
# from fastapi import FastAPI, HTTPException, Depends
# from fastapi.security import OAuth2PasswordBearer
# from pydantic import BaseModel
# import sqlite3
# import hashlib
# import jwt
# from datetime import datetime, timedelta
# 
# 
# app = FastAPI(
#     title="Secure User Management API",
#     description="FastAPI application with SQLite and JWT authentication",
#     version="1.0"
# )
# 
# 
# SECRET_KEY = "simple-secret-key-change-in-production"
# ALGORITHM = "HS256"
# 
# oauth2_scheme = OAuth2PasswordBearer(
#     tokenUrl="login"
# )
# 
# 
# # -----------------------------
# # DATABASE
# # -----------------------------
# 
# def get_connection():
#     return sqlite3.connect(
#         "users.db",
#         check_same_thread=False
#     )
# 
# 
# def create_database():
# 
#     connection = get_connection()
# 
#     cursor = connection.cursor()
# 
#     cursor.execute("""
#         CREATE TABLE IF NOT EXISTS users (
#             id INTEGER PRIMARY KEY AUTOINCREMENT,
#             username TEXT UNIQUE NOT NULL,
#             password TEXT NOT NULL
#         )
#     """)
# 
#     cursor.execute("""
#         CREATE TABLE IF NOT EXISTS items (
#             id INTEGER PRIMARY KEY AUTOINCREMENT,
#             name TEXT NOT NULL,
#             description TEXT
#         )
#     """)
# 
#     connection.commit()
#     connection.close()
# 
# 
# create_database()
# 
# 
# # -----------------------------
# # MODELS
# # -----------------------------
# 
# class User(BaseModel):
#     username: str
#     password: str
# 
# 
# class Item(BaseModel):
#     name: str
#     description: str
# 
# 
# # -----------------------------
# # PASSWORD
# # -----------------------------
# 
# def hash_password(password):
# 
#     return hashlib.sha256(
#         password.encode()
#     ).hexdigest()
# 
# 
# # -----------------------------
# # JWT
# # -----------------------------
# 
# def create_token(username):
# 
#     payload = {
#         "sub": username,
#         "exp": datetime.utcnow() + timedelta(
#             minutes=30
#         )
#     }
# 
#     return jwt.encode(
#         payload,
#         SECRET_KEY,
#         algorithm=ALGORITHM
#     )
# 
# 
# def get_current_user(
#     token: str = Depends(oauth2_scheme)
# ):
# 
#     try:
# 
#         payload = jwt.decode(
#             token,
#             SECRET_KEY,
#             algorithms=[ALGORITHM]
#         )
# 
#         username = payload.get("sub")
# 
#         if username is None:
#             raise HTTPException(
#                 status_code=401,
#                 detail="Invalid token"
#             )
# 
#         return username
# 
#     except jwt.ExpiredSignatureError:
# 
#         raise HTTPException(
#             status_code=401,
#             detail="Token expired"
#         )
# 
#     except jwt.InvalidTokenError:
# 
#         raise HTTPException(
#             status_code=401,
#             detail="Invalid token"
#         )
# 
# 
# # -----------------------------
# # HOME
# # -----------------------------
# 
# @app.get("/")
# def home():
# 
#     return {
#         "message": "Secure User Management API is running"
#     }
# 
# 
# # -----------------------------
# # REGISTER
# # -----------------------------
# 
# @app.post("/register")
# def register(user: User):
# 
#     connection = get_connection()
# 
#     cursor = connection.cursor()
# 
#     try:
# 
#         cursor.execute(
#             """
#             INSERT INTO users
#             (username, password)
#             VALUES (?, ?)
#             """,
#             (
#                 user.username,
#                 hash_password(user.password)
#             )
#         )
# 
#         connection.commit()
# 
#         return {
#             "message": "User registered successfully"
#         }
# 
#     except sqlite3.IntegrityError:
# 
#         raise HTTPException(
#             status_code=400,
#             detail="Username already exists"
#         )
# 
#     finally:
# 
#         connection.close()
# 
# 
# # -----------------------------
# # LOGIN
# # -----------------------------
# 
# @app.post("/login")
# def login(user: User):
# 
#     connection = get_connection()
# 
#     cursor = connection.cursor()
# 
#     cursor.execute(
#         """
#         SELECT username, password
#         FROM users
#         WHERE username = ?
#         """,
#         (user.username,)
#     )
# 
#     result = cursor.fetchone()
# 
#     connection.close()
# 
#     if result is None:
# 
#         raise HTTPException(
#             status_code=401,
#             detail="Invalid username or password"
#         )
# 
#     username, stored_password = result
# 
#     if hash_password(user.password) != stored_password:
# 
#         raise HTTPException(
#             status_code=401,
#             detail="Invalid username or password"
#         )
# 
#     token = create_token(username)
# 
#     return {
#         "access_token": token,
#         "token_type": "bearer"
#     }
# 
# 
# # -----------------------------
# # PROTECTED PROFILE
# # -----------------------------
# 
# @app.get("/profile")
# def profile(
#     current_user: str = Depends(get_current_user)
# ):
# 
#     return {
#         "username": current_user,
#         "message": "You accessed a protected endpoint"
#     }
# 
# 
# # -----------------------------
# # CREATE ITEM
# # -----------------------------
# 
# @app.post("/items")
# def create_item(
#     item: Item,
#     current_user: str = Depends(get_current_user)
# ):
# 
#     connection = get_connection()
# 
#     cursor = connection.cursor()
# 
#     cursor.execute(
#         """
#         INSERT INTO items
#         (name, description)
#         VALUES (?, ?)
#         """,
#         (
#             item.name,
#             item.description
#         )
#     )
# 
#     connection.commit()
# 
#     item_id = cursor.lastrowid
# 
#     connection.close()
# 
#     return {
#         "id": item_id,
#         "name": item.name,
#         "description": item.description,
#         "created_by": current_user
#     }
# 
# 
# # -----------------------------
# # GET ITEMS
# # -----------------------------
# 
# @app.get("/items")
# def get_items(
#     current_user: str = Depends(get_current_user)
# ):
# 
#     connection = get_connection()
# 
#     cursor = connection.cursor()
# 
#     cursor.execute(
#         "SELECT id, name, description FROM items"
#     )
# 
#     rows = cursor.fetchall()
# 
#     connection.close()
# 
#     return [
#         {
#             "id": row[0],
#             "name": row[1],
#             "description": row[2]
#         }
#         for row in rows
#     ]

import nest_asyncio
import uvicorn
import threading

nest_asyncio.apply()

def run_api():
    uvicorn.run(
        "project4_api:app",
        host="0.0.0.0",
        port=8000
    )

thread = threading.Thread(
    target=run_api,
    daemon=True
)

thread.start()

import nest_asyncio
import uvicorn
import threading

nest_asyncio.apply()

def run_api():
    uvicorn.run(
        "project4_api:app",
        host="0.0.0.0",
        port=8000
    )

thread = threading.Thread(
    target=run_api,
    daemon=True
)

thread.start()

import requests

register_data = {
    "username": "student",
    "password": "student123"
}

response = requests.post(
    "http://127.0.0.1:8000/register",
    json=register_data
)

print(response.status_code)
print(response.json())

response = requests.post(
    "http://127.0.0.1:8000/login",
    json=register_data
)

print(response.status_code)

login_result = response.json()

print(login_result)

token = login_result["access_token"]

print("JWT Token:")
print(token)

headers = {
    "Authorization": f"Bearer {token}"
}

response = requests.get(
    "http://127.0.0.1:8000/profile",
    headers=headers
)

print(response.status_code)
print(response.json())

item_data = {
    "name": "Python Project",
    "description": "Internship project item"
}

response = requests.post(
    "http://127.0.0.1:8000/items",
    json=item_data,
    headers=headers
)

print(response.status_code)
print(response.json())

response = requests.get(
    "http://127.0.0.1:8000/items",
    headers=headers
)

print(response.status_code)
print(response.json())

response = requests.get(
    "http://127.0.0.1:8000/profile"
)

print(response.status_code)
print(response.json())