# -*- coding: utf-8 -*-
"""Task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OPyXMtSgAIpqpUOk-mHz04lyRnfyAHf-
"""

import shutil
import os

if os.path.exists("project5_capstone"):
    shutil.rmtree("project5_capstone")

os.makedirs("project5_capstone")

print("Fresh Project 5 folder created.")

!pip install requests reportlab schedule -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile project5_capstone/report_generator.py
# 
# import requests
# import json
# import os
# from datetime import datetime
# from reportlab.lib.pagesizes import A4
# from reportlab.pdfgen import canvas
# 
# 
# BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# 
# API_URL = "https://jsonplaceholder.typicode.com/posts"
# 
# 
# def fetch_data():
# 
#     response = requests.get(
#         API_URL,
#         timeout=10
#     )
# 
#     response.raise_for_status()
# 
#     return response.json()
# 
# 
# def analyze_data(data):
# 
#     total_records = len(data)
# 
#     users = {}
# 
#     for record in data:
# 
#         user_id = record["userId"]
# 
#         users[user_id] = users.get(
#             user_id,
#             0
#         ) + 1
# 
#     most_active_user = max(
#         users,
#         key=users.get
#     )
# 
#     return {
#         "total_records": total_records,
#         "unique_users": len(users),
#         "most_active_user": most_active_user,
#         "generated_at": datetime.now().strftime(
#             "%Y-%m-%d %H:%M:%S"
#         )
#     }
# 
# 
# def save_json(data, filename):
# 
#     filepath = os.path.join(
#         BASE_DIR,
#         filename
#     )
# 
#     with open(
#         filepath,
#         "w"
#     ) as file:
# 
#         json.dump(
#             data,
#             file,
#             indent=4
#         )
# 
# 
# def generate_pdf_report(summary, filename):
# 
#     filepath = os.path.join(
#         BASE_DIR,
#         filename
#     )
# 
#     pdf = canvas.Canvas(
#         filepath,
#         pagesize=A4
#     )
# 
#     width, height = A4
# 
#     pdf.setFont(
#         "Helvetica-Bold",
#         18
#     )
# 
#     pdf.drawString(
#         50,
#         height - 60,
#         "Automated API Report"
#     )
# 
#     pdf.setFont(
#         "Helvetica",
#         12
#     )
# 
#     y = height - 110
# 
#     pdf.drawString(
#         50,
#         y,
#         f"Generated At: {summary['generated_at']}"
#     )
# 
#     y -= 30
# 
#     pdf.drawString(
#         50,
#         y,
#         f"Total Records: {summary['total_records']}"
#     )
# 
#     y -= 30
# 
#     pdf.drawString(
#         50,
#         y,
#         f"Unique Users: {summary['unique_users']}"
#     )
# 
#     y -= 30
# 
#     pdf.drawString(
#         50,
#         y,
#         f"Most Active User: {summary['most_active_user']}"
#     )
# 
#     y -= 50
# 
#     pdf.drawString(
#         50,
#         y,
#         "Report generated automatically using Python."
#     )
# 
#     pdf.save()
# 
# 
# def generate_report():
# 
#     print("Starting automated report generation...")
# 
#     try:
# 
#         data = fetch_data()
# 
#         print(
#             f"Downloaded {len(data)} records."
#         )
# 
#         summary = analyze_data(data)
# 
#         save_json(
#             data,
#             "raw_data.json"
#         )
# 
#         save_json(
#             summary,
#             "summary.json"
#         )
# 
#         generate_pdf_report(
#             summary,
#             "automated_report.pdf"
#         )
# 
#         print(
#             "Report generation completed successfully."
#         )
# 
#         return summary
# 
#     except requests.RequestException as e:
# 
#         print(
#             "API request failed:",
#             e
#         )
# 
#     except Exception as e:
# 
#         print(
#             "Unexpected error:",
#             e
#         )
# 
# 
# if __name__ == "__main__":
# 
#     result = generate_report()
# 
#     if result:
# 
#         print("\nSUMMARY")
#         print("=" * 40)
# 
#         for key, value in result.items():
# 
#             print(
#                 f"{key}: {value}"
#             )

!python project5_capstone/report_generator.py

import os

print(os.listdir("project5_capstone"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile project5_capstone/cli.py
# 
# import argparse
# from report_generator import generate_report
# 
# 
# def main():
# 
#     parser = argparse.ArgumentParser(
#         description="Automated API Report Generator"
#     )
# 
#     parser.add_argument(
#         "--generate",
#         action="store_true",
#         help="Generate the report"
#     )
# 
#     args = parser.parse_args()
# 
#     if args.generate:
# 
#         result = generate_report()
# 
#         if result:
#             print("\nCLI execution completed.")
# 
#     else:
# 
#         print(
#             "Use --generate to create the report."
#         )
# 
# 
# if __name__ == "__main__":
# 
#     main()

!cd project5_capstone && python cli.py --generate

import json

with open(
    "project5_capstone/summary.json",
    "r"
) as file:

    summary = json.load(file)

print(
    json.dumps(
        summary,
        indent=4
    )
)

import schedule
import time

from project5_capstone.report_generator import generate_report


def scheduled_job():

    print("\nScheduled job started.")

    try:

        result = generate_report()

        if result:
            print("Scheduled job completed.")

    except Exception as e:

        print("Scheduled job failed:", e)


schedule.every(1).hours.do(
    scheduled_job
)

print("Scheduler started.")
print("The report will be generated every hour.")

scheduled_job()