# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKe9hcaGlizC53Ao6o43m_lE-ZpMKbgi
"""

import os

os.makedirs("project2_banking", exist_ok=True)

print("Project 2 folder created.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile project2_banking/banking.py
# 
# import json
# 
# 
# class InsufficientFundsError(Exception):
#     pass
# 
# 
# class InvalidAmountError(Exception):
#     pass
# 
# 
# class Account:
#     def __init__(self, account_number, holder_name, balance=0):
#         self._account_number = account_number
#         self._holder_name = holder_name
#         self._balance = balance
# 
#     @property
#     def account_number(self):
#         return self._account_number
# 
#     @property
#     def holder_name(self):
#         return self._holder_name
# 
#     @property
#     def balance(self):
#         return self._balance
# 
#     def deposit(self, amount):
#         if amount <= 0:
#             raise InvalidAmountError("Deposit amount must be greater than zero.")
# 
#         self._balance += amount
# 
#     def withdraw(self, amount):
#         if amount <= 0:
#             raise InvalidAmountError("Withdrawal amount must be greater than zero.")
# 
#         if amount > self._balance:
#             raise InsufficientFundsError("Insufficient balance.")
# 
#         self._balance -= amount
# 
#     def account_type(self):
#         return "General Account"
# 
#     def to_dict(self):
#         return {
#             "account_number": self.account_number,
#             "holder_name": self.holder_name,
#             "balance": self.balance,
#             "account_type": self.account_type()
#         }
# 
# 
# class SavingsAccount(Account):
# 
#     def __init__(self, account_number, holder_name, balance=0, interest_rate=0.04):
#         super().__init__(account_number, holder_name, balance)
#         self.interest_rate = interest_rate
# 
#     def account_type(self):
#         return "Savings Account"
# 
#     def calculate_interest(self):
#         return self.balance * self.interest_rate
# 
# 
# class CurrentAccount(Account):
# 
#     def __init__(self, account_number, holder_name, balance=0, overdraft_limit=1000):
#         super().__init__(account_number, holder_name, balance)
#         self.overdraft_limit = overdraft_limit
# 
#     def account_type(self):
#         return "Current Account"
# 
#     def withdraw(self, amount):
#         if amount <= 0:
#             raise InvalidAmountError("Withdrawal amount must be greater than zero.")
# 
#         if amount > self.balance + self.overdraft_limit:
#             raise InsufficientFundsError("Overdraft limit exceeded.")
# 
#         self._balance -= amount
# 
# 
# class BankingLedger:
#     def __init__(self):
#         self.accounts = {}
# 
#     def add_account(self, account):
#         self.accounts[account.account_number] = account
# 
#     def get_account(self, account_number):
#         if account_number not in self.accounts:
#             raise ValueError("Account not found.")
# 
#         return self.accounts[account_number]
# 
#     def transfer(self, from_account, to_account, amount):
#         sender = self.get_account(from_account)
#         receiver = self.get_account(to_account)
# 
#         sender.withdraw(amount)
#         receiver.deposit(amount)
# 
#     def save(self, filename="bank_accounts.json"):
#         data = []
# 
#         for account in self.accounts.values():
#             data.append(account.to_dict())
# 
#         with open(filename, "w") as file:
#             json.dump(data, file, indent=4)
# 
#     def display_accounts(self):
#         print("=" * 60)
#         print("BANKING LEDGER")
#         print("=" * 60)
# 
#         for account in self.accounts.values():
#             print(
#                 f"{account.account_number} | "
#                 f"{account.holder_name} | "
#                 f"{account.account_type()} | "
#                 f"Balance: ₹{account.balance:.2f}"
#             )

import sys

sys.path.append("/content/project2_banking")

from banking import (
    Account,
    SavingsAccount,
    CurrentAccount,
    BankingLedger,
    InsufficientFundsError
)

ledger = BankingLedger()

account1 = SavingsAccount(
    "S001",
    "Aishwarya",
    10000
)

account2 = CurrentAccount(
    "C001",
    "Rahul",
    5000
)

ledger.add_account(account1)
ledger.add_account(account2)

ledger.display_accounts()

account1.deposit(2000)

account1.withdraw(1500)

print("Savings Account Balance:", account1.balance)

account1.deposit(2000)

account1.withdraw(1500)

print("Savings Account Balance:", account1.balance)

ledger.save()

print("Bank account data saved successfully.")

import json

with open("bank_accounts.json", "r") as file:
    data = json.load(file)

print(json.dumps(data, indent=4))

"""TESTING"""

!pip install pytest -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile project2_banking/test_banking.py
# 
# import sys
# sys.path.append("/content/project2_banking")
# 
# from banking import (
#     SavingsAccount,
#     CurrentAccount,
#     BankingLedger,
#     InsufficientFundsError,
#     InvalidAmountError
# )
# 
# 
# def test_deposit():
#     account = SavingsAccount("S1", "Test User", 1000)
# 
#     account.deposit(500)
# 
#     assert account.balance == 1500
# 
# 
# def test_withdraw():
#     account = SavingsAccount("S1", "Test User", 1000)
# 
#     account.withdraw(300)
# 
#     assert account.balance == 700
# 
# 
# def test_transfer():
#     ledger = BankingLedger()
# 
#     account1 = SavingsAccount("S1", "User 1", 1000)
#     account2 = SavingsAccount("S2", "User 2", 500)
# 
#     ledger.add_account(account1)
#     ledger.add_account(account2)
# 
#     ledger.transfer("S1", "S2", 200)
# 
#     assert account1.balance == 800
#     assert account2.balance == 700
# 
# 
# def test_insufficient_balance():
#     account = SavingsAccount("S1", "User", 500)
# 
#     try:
#         account.withdraw(1000)
#         assert False
#     except InsufficientFundsError:
#         assert True
# 
# 
# def test_invalid_deposit():
#     account = SavingsAccount("S1", "User", 500)
# 
#     try:
#         account.deposit(-100)
#         assert False
#     except InvalidAmountError:
#         assert True

!pytest project2_banking/test_banking.py -v